name: tabnews
description: A new Flutter project.

publish_to: "none"
repository: https://github.com/softyesti/tabnews_client

version: 0.0.1+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  dart_mappable: ^4.0.1
  get: ^4.6.6
  ionicons: ^0.2.2
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.20+1
  url_launcher: ^6.2.5
  markdown: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  dart_mappable_builder: ^4.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/adaptive_icon.png"
  adaptive_icon_background: "assets/adaptive_icon_bg.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#0D1117"
    theme_color: "#0D1117"

flutter_native_splash:
  color: "#0D1117"
  android: true
  ios: true
  web: true
  android_12:
    branding: assets/branding.png
